In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score  ## precision和recall对应用户精度和生产者精度。
from sklearn.model_selection import train_test_split
import numpy as np
import pickle 

In [51]:
path_numpy = 'data/Section-7/sams_array.npy'
sams = np.load(path_numpy)
sams_fea, sams_label = sams[:,0:6], sams[:,6]


In [53]:
sams_fea = sams_fea/(10000-0)
sams_fea

array([[0.1254, 0.126 , 0.12  , 0.1139, 0.1137, 0.1126],
       [0.1258, 0.1251, 0.1197, 0.1133, 0.1121, 0.1115],
       [0.1256, 0.126 , 0.1189, 0.113 , 0.113 , 0.1124],
       ...,
       [0.1684, 0.1844, 0.2072, 0.3512, 0.3835, 0.2668],
       [0.1808, 0.1908, 0.2014, 0.2182, 0.2602, 0.2462],
       [0.1756, 0.1842, 0.1955, 0.223 , 0.2669, 0.2499]])

In [54]:
X_train, X_test, y_train, y_test = train_test_split(sams_fea, sams_label, test_size=0.3, random_state=42)
print(X_train.shape)
print(X_test.shape)

(336, 6)
(144, 6)


In [55]:
model_rf = RandomForestClassifier(random_state=42)


In [56]:
model_rf = model_rf.fit(X=X_train, y=y_train)

In [57]:
y_test_pred = model_rf.predict(X_test)


In [58]:
print(X_test[11])
model_rf.predict(np.array(X_test[11].reshape(1,6)).reshape(1,6))


[0.347  0.377  0.4264 0.403  0.4174 0.4182]


array([1])

In [59]:
## 模型加载
path_model = 'data/Section-7/model_rf.pickle'
with open(path_model, 'rb') as file:
  model_rf_ = pickle.load(file)

model_rf_.predict(np.array(X_test[11].reshape(1,6)).reshape(1,6))


array([0])

In [60]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true=y_test, y_pred=y_test_pred, labels=[0,1])


array([[78,  0],
       [ 0, 66]], dtype=int64)

In [61]:
oa = accuracy_score(y_true=y_test, y_pred=y_test_pred)
print(oa)
precision = precision_score(y_true=y_test, y_pred=y_test_pred)
print(precision)
recall = recall_score(y_true=y_test, y_pred=y_test_pred)
print(recall)



1.0
1.0
1.0


In [ ]:

# path_model = 'data/Section-7/model_rf.pickle'
# with open(path_model, 'wb') as file:
#     pickle.dump(model_rf, file)
